### ISSUE TITLE
Future plans

### ISSUE THREAD

**Issue by Safihre** [caronc/newsreap#2]
Let me start by saying I am very happy to see all your work! Even though I can't run it yet on my machine, your code looks very good, very well structured, almost textbook like! It is a delight to read.
Are you a python developer in daily life? :)

This of course makes me wonder what your plans are with this code? Just for fun, or would you also be interested in working with us, SABnzbd?
I only joined SABnzbd 1 year ago and have re-vamped the interface, but the download core is still very old (like, 2004) and in dire need of revamping. Otherwise in a few years it really won't be able to keep up anymore.. But I just don't have the skills for it or don't even know where to start, and the others hin the project ave less and less time nowadays.

Would you be interested in working with us? And do you think your code will be fast for downloading, in terms of speed and CPU usage?
Getting your project into SABnzbd would of course require a bit of a different direction and additional features, but also 100.000+ users :hamster:

**Comment by caronc** [comment]
Hah, thank you for your kind words! I am indeed a developer in the real world, and love to code as a hobbyist on the side.

I've made so much headway with this tool; the back-end is almost entirely written now and with unit tests to back it up (still many more tests to write). I really want to add a posting functionality to support obfuscation, par2, rar/zip support, etc).... some day... It's a fun hobby to learn how usenet works! :)

Unfortunately I must decline your offer of being part of SABnzbd though.  I do love your product, but I'd really like to make this tool (NewsReap) do what it actually says it should do. The other issue I'd have is promising any sort of reliability.  I'll be home for 1 week and put in lots of hours when not with the family, but then things come up at work... or at home and then I'll be MIA for 2 weeks to a month.  I just couldn't properly commit and/or be reliable for you or your fantastic team.

All that said, I don't mind having a look at things you and/or your team get stumped on (depending on the effort level i may or may not commit to it though). What are some of the goals you have for its future?

Were you looking at adding features? Or re-factoring sections of it?  I know you mentioned cpu becomes a bottleneck with yEnc in [another post](https://github.com/caronc/nzb-notify/issues/5#issuecomment-233749614)?

**Comment by Safihre** [comment]
I understand :) 
Well, we really need to re-think the whole download-decode part, from the ground up. All our supporting functions (UI, Config, par2, unrar, scripts) are good, but it's the downloading that needs work.
Really wonder how your solution using gevent performs in terms of CPU% and download-speed!

**Comment by caronc** [comment]
IMO Python is fun to write and usually to read. But it's so bloody slow to do anything that involves a lot of calculations (like yEnc decoding for example). Python is also _absolutely horrible_ with memory management at the trade off of making the coding aspect of it so flexible and easy to do (why people love it). 

They say you can do something many ways with Python which is totally true. But truly, there are very few _right ways_. String manipulation for example is really bad... really, really, really bad (and slow). If you can get away with manipulating your string(s) with a ByteIO (or StringIO) object instead, you can gain speed here for sure (depending on the implementation). The trade off is that these objects aren't that fun to work with. It can become quiet a design change in an existing app too adapting them.

Alternatively, getting stuff pushed to a C/C++ callable function is even better!  I don't use Windows, but is it really difficult to get the yEnc plugin installed with it? I think you just have to have [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-ca/download/details.aspx?id=44266) installed ahead of time and __pip__ will do the rest (I'm not sure)? SABnzbd would certainly see a performance boost here (I realize you know this already). :)

Personally, I think SABnzbd tries so hard to be compatible with everything and everyone. It literally just works right out of the box allowing anyone to just pick up and go (which is awesome BTW). I also realize you have a huge (very loyal and positive) following because of this! But because SABnzbd is truly a pure Python solution, it's quite possible you're just hitting that language limitation. You might just be at the point where performance increases will marginal at best from the tweaks that you do.

So to compromise, maybe you could branch SABnzbd? Basically you'd have one pure Python solution (what you have already now) with its know limitations. Then a second (new) branch where you'd harness the power of what people have done overcome these limitations. You would _definitely_ see a performance increase here (for sure), but your target audience would inevitably shrink with the forked version (most might just stick with the old one the second they hit a problem). 

Varying versions of Python and Operating Systems mean varying versions of Python sub-libraries (gevent is a really good example of this and is rapidly changing). Thus debugging your app gets tougher because the problems people face might turn out to not be yours.

That said, gevent is nice because it takes a lot of the Python functionality limited by the GIL (sockets, threading, event handling) and moves it out of Python (back into more C/C++ libraries). It is a fantastic performance boost!

Sorry to rant so much, but I'm very curious of your thoughts?

**Comment by Safihre** [comment]
Yes, people try to run SABnzbd on a shoe box basically and then get annoyed when it doesn't work...... Sigh!

Regarding yEnc: we use the ```_yenc``` C module of course, without it SABnzbd is barely usable. It's provided in our installers for Windows, OSX and Ubuntu, so about 98% of installations, luckily! 
So for those installations we could port more stuff into C++, but none of us has any really experience with it :/
For now it will be python all the way...

I think currently too many parts of our code are only written 90% optimal, and this 10% of the separate parts is starting to add up to a general slowness. We also would love to try things like PyPy since it seems to offer great speed increases, but just seem unable to get it to work..
All of us at SABnzbd are not hard-core coders in our daily jobs, and definitely don't know the tiny details of Python that we need or any other approaches like gevent.
We just don't know about it and other speed-tweaks... So therefore we also can't implement it.
But I have the feeling you are really aware of modern techniques and speed-tweaks! 

So again: can't wait to speed-test your solution and then (hopefully with your help) translate it into SABnzbd!

**Comment by caronc** [comment]
@Safihre you're very pleasant to talk to! Thank you for your feedback and input.  If you don't mind i'm just going to close this ticket, but leave your other one open.  Windows support would be ideal at some point!

**Comment by Safihre** [comment]
Sounds good :)
